AWSTemplateFormatVersion: '2010-09-09'
Description: Stream logs from AWS to Datadog using Kinesis Firehose and CloudWatch Logs

Resources:
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/example-log-group
      RetentionInDays: 14

  KinesisFirehoseDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: aws-to-datadog-stream
      DeliveryStreamType: DirectPut
      HttpEndpointDestinationConfiguration:
        EndpointConfiguration:
          Url: !Sub "https://http-intake.logs.datadoghq.com/v1/input/${DatadogApiKey}"
          AccessKey: !Ref DatadogApiKey
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 5
        S3BackupMode: FailedDataOnly
        S3Configuration:
          BucketARN: !Sub "arn:aws:s3:::your-backup-bucket"
          RoleARN: !GetAtt FirehoseDeliveryRole.Arn

  FirehoseDeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FirehoseToDatadogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::your-backup-bucket"
                  - !Sub "arn:aws:s3:::your-backup-bucket/*"

Parameters:
  DatadogApiKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /datadog/apiKey
    Description: Datadog API Key stored in AWS Systems Manager Parameter Store

