AWSTemplateFormatVersion: '2010-09-09'
Description: Stream logs from an existing AWS CloudWatch Log Group to Datadog using Kinesis Firehose

Parameters:
  ExistingLogGroupName:
    Type: String
    Description: The name of the existing CloudWatch Log Group
  DatadogApiKey:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/datadog/apiKey'
  DatadogHost:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/datadog/host'

Resources:
  KinesisFirehoseDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: aws-to-datadog-stream
      DeliveryStreamType: DirectPut
      HttpEndpointDestinationConfiguration:
        EndpointConfiguration:
          Url: !Sub "https://${DatadogHost}/v1/input/${DatadogApiKey}"
          AccessKey: !Ref DatadogApiKey
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 5
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref ExistingLogGroupName
          LogStreamName: FirehoseDelivery
        RequestConfiguration:
          ContentEncoding: "GZIP"
        S3BackupMode: FailedDataOnly
        S3Configuration:
          BucketARN: !Sub "arn:aws:s3:::your-backup-bucket"
          RoleARN: !GetAtt FirehoseDeliveryRole.Arn

  FirehoseDeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FirehoseToDatadogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::your-backup-bucket"
                  - !Sub "arn:aws:s3:::your-backup-bucket/*"

  CloudWatchLogsSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !GetAtt KinesisFirehoseDeliveryStream.Arn
      FilterPattern: ""
      LogGroupName: !Ref ExistingLogGroupName
      RoleArn: !GetAtt FirehoseDeliveryRole.Arn
